### ISSUE TITLE
발표준비

### ISSUE THREAD

**Issue by ChoiWheatley** [ChoiWheatley/swjungle-week-00#3]
# 발표에 들어갈 내용
- 와이어프레임 설명 #2 (1분)
- 구현에 필요한 기능들 (2분)
- 어떤 협업툴 사용할건지 (1분)
- 기술스택 (1분)

**Comment by choihyerln** [comment]
8/8(화) 프로젝트 주제 발표 피드백

- 프롬프트 엔지니어링 시간을 버릴 수 있음
- 생각보다 복잡한 UI 될 수 있음
- gpt가 이상한 말 할 수 있으니 프롬프트 잘 짜야함 -> 시간 분배 잘 해볼 것
- placeholder 넣지 앟는 걸 추천

내가 쓰고 있는 기술들에 대한 이해를 기반으로 구현해나가자
조원들끼리 서로 질문하는 시간 가지기!
